# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d715dcba95df4f667d0da71fb5a4e9a96483202ceef44eb5de0801653c64d7a7a7fa8c8c2ee59f5211f4aeea15ed9668fb0caddd4f2dbd52fb85177d9ebf32c

test:
  secret_key_base: 1a6f2021c0ff8e2b06355ffb1ddc2a58221d9f26be5a7000400b40c764395f86d1082de4548169ac2c82f4660072ed357de80d02f811f281f4028f40f5f31901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
